track:
  color: "#ff0000"
  linewidth: 2

trees:
  color: "green"
  size: 1

streets:
  color: "#000000"
  linewidth: 1

buildings:
  color: "#808080"
  linewidth: 1
  alpha: 0.7

rivers:
  color: "#0000ff"
  linewidth: 2

amenity:
  color: "salmon"
  linewidth: 1
  alpha: 0.7

shop:
  color: "orange"
  linewidth: 1
  alpha: 1

cycleway:
  color: "darkblue"
  linewidth: 1
  alpha: 1

#test:
#  color: 'brown'
#  linewidth: 1
#  alpha: 0.9
