track:
  color: "#ff0000"
  linewidth: 2

trees:
  color: "#00ff00"
  size: 5

streets:
  color: "#000000"
  linewidth: 1

buildings:
  color: "#808080"
  linewidth: 1
  alpha: 0.7

rivers:
  color: "#0000ff"
  linewidth: 2
